### PR TITLE
Fixed bug in apply command

### LINKED ISSUE #62: Unable to apply for new repo
When creating a new repository with `apply` command, `gitstrap` fails with error: `404: repository doesn't exist`, while it's still possible to create repo using same specification file with `create` command. The `gitstrap` should create a new repository with `apply` if it doesn't exist.

### PR DESCRIPTION
**Pull request by OrlovM**
Fixed #62 in Gitstrap.applyRepo

Bug caused the inability to create repo if it does not exist with apply command.

Several GitHub API methods return boolean responses indicated by the HTTP
status code in the response (true indicated by a 204, false indicated by a 404)

Github.RepositoriesService.Get method returned ErrorResponse if repo did not exist.

Fixed TeamExist, OrgExist and RepoExist fuctions: аdded utility function parseBoolResponse, that determines the response result and hides the 404 error. Any other error will be returned through as-is.

### CODE REVIEW

File: internal/github/utils.go [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+
+import (
+	"net/http"
+
+	gh "github.com/google/go-github/v33/github"
+)
+
+// parseBoolResponse determines the boolean result from a GitHub API response.
+// Several GitHub API methods return boolean responses indicated by the HTTP
+// status code in the response (true indicated by a 204, false indicated by a
```
Comment (g4s8) [inline internal/github/utils.go:11]: Why 204 status means true?

File: internal/github/utils.go [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+// 404). This helper function will determine that result and hide the 404
+// error if present. Any other error will be returned through as-is.
+func parseBoolResponse(err error) (bool, error) {
```
Comment (g4s8) [inline internal/github/utils.go:14]: This name seems not really correct: this method parses error into bool, not the response or bool, so I'd change it into `isErrNotFound(error)`

**Review by g4s8 — CHANGES_REQUESTED** [review]
@OrlovM please see my comments

File: internal/github/utils.go (hunk 1 above)
Comment (OrlovM) [reply internal/github/utils.go:13]: It does not refer to Github Get methods. Only bool responses return 204 or 404. For example [this](https://docs.github.com/en/rest/reference/repos#check-if-vulnerability-alerts-are-enabled-for-a-repository) or [this](https://docs.github.com/en/rest/reference/repos#check-if-a-user-is-a-repository-collaborator).
In case of get method it returns 200 or 404.
Corrected the function comment.

File: internal/github/utils.go (hunk 2 above)
Comment (OrlovM) [reply internal/github/utils.go]: isErrNotFound does not seem correct too. 
I agree, function operates only with error. But at result it determines the condition of the response(true, false or error), not only the existence or type of error.
In other words it resolves response status by error.

**Review by g4s8 — APPROVED** [review]
@OrlovM thanks
